name: Make check/distcheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build with UCS2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: Autogen && configure
      run: |
        ./autogen.sh
        ./configure
    - name: Make
      run: make
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs2.log
        path: tests/test-suite.log
    - name: Make distcheck
      run: make distcheck

  build-asan:
    name: Build with UCS2 and asan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: Autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=address -g" ./configure
    - name: Make
      run: make
    - name: Make check
      run: ASAN_OPTIONS=detect_leaks=0 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs2-asan.log
        path: tests/test-suite.log

  build-lsan:
    name: Build with UCS2 and lsan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: Autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=leak -g" ./configure
    - name: Make
      run: make
    - name: Make check
      run: LSAN_OPTIONS=fast_unwind_on_malloc=0 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs2-lsan.log
        path: tests/test-suite.log

  build-usan:
    name: Build with UCS2 and usan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: Autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=undefined -g" ./configure
    - name: Make
      run: make
    - name: Make check
      run: UBSAN_OPTIONS=halt_on_error=1 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs2-usan.log
        path: tests/test-suite.log

  build-ucs4:
    name: Build with UCS4

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev texinfo texlive
    - name: autogen && configure
      run: |
        ./autogen.sh
        ./configure --enable-ucs4
    - name: Make
      run: make
    - name: Make check
      run: make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs4.log
        path: tests/test-suite.log
    - name: Make distcheck
      run: make distcheck
    - name: Install Go
      run: sudo apt-get install -y golang
    - name: Run the metadata test
      run: make -C extra/generate-display-names
    - name: Store the log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: generate-display-names.log
        path: extra/generate-display-names/generate.log

  build-ucs4-asan:
    name: Build with UCS4 and asan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=address -g" ./configure --enable-ucs4
    - name: Make
      run: make
    - name: Make check
      run: ASAN_OPTIONS=detect_leaks=0 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs4-asan.log
        path: tests/test-suite.log

  build-ucs4-lsan:
    name: Build with UCS4 and lsan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=leak -g" ./configure --enable-ucs4
    - name: Make
      run: make
    - name: Make check
      run: LSAN_OPTIONS=fast_unwind_on_malloc=0 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs4-lsan.log
        path: tests/test-suite.log

  build-ucs4-usan:
    name: Build with UCS4 and usan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
    - name: autogen && configure
      run: |
        ./autogen.sh
        CFLAGS="-fsanitize=undefined -g" ./configure --enable-ucs4
    - name: Make
      run: make
    - name: Make check
      run: UBSAN_OPTIONS=halt_on_error=1 make check
    - name: Store the test suite log
      if: ${{ always() }} # store the test suite log even if the tests failed
      uses: actions/upload-artifact@v2
      with:
        name: test-suite-ucs4-usan.log
        path: tests/test-suite.log
