name: Run sanitizer checks

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'

  pull_request:
    branches: [ master ]
    paths:
      - '**.h'
      - '**.c'

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with ${{ matrix.sanitizer }} sanitizer for ${{ matrix.ucs }}
    strategy:
      matrix:
        ucs: [ucs2, ucs4]
        sanitizer: [address, leak, undefined]
        include:
          - sanitizer: "address"
            options: "ASAN_OPTIONS=detect_leaks=0"
          - sanitizer: "leak"
            options: "LSAN_OPTIONS=fast_unwind_on_malloc=0"
          - sanitizer: "undefined"
            options: "UBSAN_OPTIONS=halt_on_error=1"
    steps:
      - uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libyaml-dev
      - name: Autogen
        run: ./autogen.sh
      - name: Configure
        run: CFLAGS="-fsanitize=${{ matrix.sanitizer }} -g" ./configure
        if: matrix.ucs == 'ucs2'
      - name: Configure with ucs4
        run: CFLAGS="-fsanitize=${{ matrix.sanitizer }} -g" ./configure --enable-ucs4
        if: matrix.ucs == 'ucs4'
      - name: Make check
        run: ${{ matrix.options }} make check
      - name: Store the test suite log
        if: ${{ always() }} # store the test suite log even if the tests failed
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: test-suite-${{ matrix.ucs }}-${{ matrix.sanitizer }}.log
          path: tests/test-suite.log
